package(default_visibility = ["//visibility:public"])

cc_library(
    name = "stl",
    srcs = [
        "directory.cc",
        "file.cc",
        "path.cc",
        "stl.cc",
        "string.cc",
        "time.cc",
    ],
    hdrs = [
        "stdafx.h",
    ],
    includes = ["../../include"],
    linkopts = ["-lm"],
    deps = [
    ],
)
